name: Check if users are online
on:
  schedule:
    - cron: "*/6 11-23 * * *"
    - cron: "*/6 0-1 * * *"
  #workflow_dispatch:
permissions:
  contents: write
jobs:
  resources:
    name: Check if users are online
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create env file
        run: |
          touch .env
          echo EMAIL=${{ secrets.EMAIL }} >> .env
          echo EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} >> .env
          echo USERS=${{ secrets.USERS }} >> .env
          echo USER_ID=${{ secrets.USER_ID }} >> .env
          echo OFFLINE_USERS=${{ secrets.OFFLINE_USERS }} >> .env
          echo BASE_URL=${{ secrets.BASE_URL }} >> .env
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - name: Check if users are online
        run: yarn run checkIfUserIsOnline
