name: Check if users are offline
on:
  schedule:
    - cron: "*/6 13-17 * * 1-5" # every weekday every six minutes starting at 10:00am and ending at 03:00pm
  #workflow_dispatch:
permissions:
  contents: write
jobs:
  resources:
    name: Check if users are offline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create env file
        run: |
          touch .env
          echo EMAIL=${{ secrets.EMAIL }} >> .env
          echo EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} >> .env
          echo USERS=${{ secrets.USERS }} >> .env
          echo USER_ID=${{ secrets.USER_ID }} >> .env
          echo OFFLINE_USERS=${{ secrets.OFFLINE_USERS }} >> .env
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - name: Check if users are offline
        run: yarn run checkIfUserIsOffline
