name: Check if user got achievement
on:
  schedule:
    - cron: "0 8-23/2 29 12 0" # every 2 hours starting at 08:00am and ending at 11:00pm
  #workflow_dispatch:
permissions:
  contents: write
jobs:
  resources:
    name: Check if user got achievement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create env file
        run: |
          touch .env
          echo EMAIL=${{ secrets.EMAIL }} >> .env
          echo EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} >> .env
          echo USERS=${{ secrets.USERS }} >> .env
          echo USER_ID=${{ secrets.USER_ID }} >> .env
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - name: Check if users are online
        run: yarn run checkIfUserGotAchievement
