name: Check if users are online
on:
  schedule:
    - cron: "*/6 * * * 6,0"
  #workflow_dispatch:
permissions:
  contents: write
jobs:
  resources:
    name: Check if users are online
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create env file
        run: |
          touch .env
          echo EMAIL=${{ secrets.EMAIL }} >> .env
          echo EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} >> .env
          echo USERS=${{ secrets.USERS }} >> .env
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - name: Check if users are online
        run: yarn run checkIfUserIsOnline
